//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Abstract {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Local {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Local() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Abstract.Local", typeof(Local).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExceedRecurseCount.
        /// </summary>
        internal static string ExceedRecurseCount {
            get {
                return ResourceManager.GetString("ExceedRecurseCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidDataSource.
        /// </summary>
        internal static string InvalidDataSource {
            get {
                return ResourceManager.GetString("InvalidDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not send messageType &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidMessageTypeA {
            get {
                return ResourceManager.GetString("InvalidMessageTypeA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A default ServiceLocator could not be bound. Ether setup your default service locator or specify a service locator or none..
        /// </summary>
        internal static string InvalidServiceBusDefaultServiceLocator {
            get {
                return ResourceManager.GetString("InvalidServiceBusDefaultServiceLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve serviceType &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidServiceTypeA {
            get {
                return ResourceManager.GetString("InvalidServiceTypeA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve serviceType &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string InvalidServiceTypeAB {
            get {
                return ResourceManager.GetString("InvalidServiceTypeAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RedefineCacheDependency.
        /// </summary>
        internal static string RedefineCacheDependency {
            get {
                return ResourceManager.GetString("RedefineCacheDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RedefineDataCacheAB.
        /// </summary>
        internal static string RedefineDataCacheAB {
            get {
                return ResourceManager.GetString("RedefineDataCacheAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RedefineIDA.
        /// </summary>
        internal static string RedefineIDA {
            get {
                return ResourceManager.GetString("RedefineIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScopeCharacterNotAllowedA.
        /// </summary>
        internal static string ScopeCharacterNotAllowedA {
            get {
                return ResourceManager.GetString("ScopeCharacterNotAllowedA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UndefinedDataCacheRegistrationA.
        /// </summary>
        internal static string UndefinedDataCacheRegistrationA {
            get {
                return ResourceManager.GetString("UndefinedDataCacheRegistrationA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UndefinedDataCacheRegistrationAB.
        /// </summary>
        internal static string UndefinedDataCacheRegistrationAB {
            get {
                return ResourceManager.GetString("UndefinedDataCacheRegistrationAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UndefinedServiceBusProvider.
        /// </summary>
        internal static string UndefinedServiceBusProvider {
            get {
                return ResourceManager.GetString("UndefinedServiceBusProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UndefinedServiceLocatorProvider.
        /// </summary>
        internal static string UndefinedServiceLocatorProvider {
            get {
                return ResourceManager.GetString("UndefinedServiceLocatorProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UndefinedServiceLogProvider.
        /// </summary>
        internal static string UndefinedServiceLogProvider {
            get {
                return ResourceManager.GetString("UndefinedServiceLogProvider", resourceCulture);
            }
        }
    }
}
